### PR TITLE
add/gather examples for new dotty features

### PR DESCRIPTION
**Pull request by ferhtaydn**
Code examples for the new features of `dotty` from the documentations and blogs of `epfl` besides small additions by me.

### CODE REVIEW

**Comment by ferhtaydn** [comment]
hi @nicolasstucki @felixmulder, I added multiple main files but CI is expecting a single `run` command. We may change it to `run-main TraitParams` or I can gather all run codes to a single main file.

**Comment by felixmulder** [comment]
@ferhtaydn - you could run it as something like:

```bash
$ sbt ";run-main prog1 ;run-main prog2 ;run-main prog..."
```

To get all of them in a single run :)

**Comment by ferhtaydn** [comment]
thanks @felixmulder, so if you can change travis `sbt run` command to `sbt ";run-main EnumTypes ;run-main ImplicitFunctions ;run-main ImplicitParams ;run-main IntersectionTypes ;run-main TypeLambdas ;run-main TraitParams ;run-main UnionTypes" it would pass.

**Comment by smarter** [comment]
My suggestion would be to rename all the `main` methods to `test` and add a `Main.scala` with a `main` that calls all the `test` methods.

**Comment by ferhtaydn** [comment]
Thanks to all, I made the change and squash the commits, I think it is ready to be merged! :)

**Comment by felixmulder** [comment]
Thanks @ferhtaydn! :tada:

**Pull request merged**
