### PR TITLE
Release Dotty 0.13.0-RC1 for mill

### PR DESCRIPTION
**Pull request by biboudis**
Update the versions and rebase to get the changes of the new files.
Now it raises the good old `CompilerInterface`, this is related to the broken bridge issue, right?

Related to https://github.com/lampepfl/dotty/pull/5596

```shell
root.compile java.lang.ClassNotFoundException: xsbt.CompilerInterface
    java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    java.lang.Class.forName0(Native Method)
    java.lang.Class.forName(Class.java:348)
    sbt.internal.inc.AnalyzingCompiler.getInterfaceClass(AnalyzingCompiler.scala:267)
    sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:234)
    sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala:134)
    sbt.internal.inc.AnalyzingCompiler.newCachedCompiler(AnalyzingCompiler.scala
```

### CODE REVIEW

**Comment by smarter** [comment]
>  Now it raises the good old CompilerInterface, this is related to the broken bridge issue, right?

Someone needs to add support for the new bridge setup based on a binary jar instead of sources, until then, we can't upgrade the mill project.

**Comment by smarter** [comment]
Looks like someone fixed mill to get the compile-the-bridge-from-sources working, so you should be able to merge this PR once a new mill release is out: https://github.com/lihaoyi/mill/pull/569

**Comment by biboudis** [comment]
Oh! Perfect. Will stay on top of this. Thx!

**Comment by smarter** [comment]
mill 0.4.0 has been released so this should work now.

**Comment by biboudis** [comment]
@anatoliykmetyuk this PR rebased the changes for mill on top of master. Maybe we should re-rebase and check if mill works. If yes then we can re-include it on our release cycle.

**Pull request merged**
