### PR TITLE
Update SBT Version to 1.3.4

### PR DESCRIPTION
**Pull request by Mikhail-Sosnin**

### CODE REVIEW

**Comment by Mikhail-Sosnin** [comment]
@bishabosha could you please take a look when you have free time?

**Comment by bishabosha** [comment]
I guess we'll have to wait judging by the comment on the other PR - https://github.com/lampepfl/dotty.g8/pull/15#issuecomment-559745454

**Comment by FabioPinheiro** [comment]
This ticket can be closed. Seems that was already done in the meantime.

**Comment by bishabosha** [comment]
@FabioPinheiro thanks for the catch

**Pull request closed without merging**
